name: Main CI

on:
  pull_request:
    branches:    
      - main

env:
  RES_PREFIX: bord
  AWS_DEFAULT_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NODE_VERSION: 18.X

jobs:
  build:
    runs-on: ubuntu-latest

      # can use role directly https://github.com/aws-actions/configure-aws-credentials
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     - name: Build
#       id: build-image
#       run: |
#         cdk init
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm install -g aws-cdk 
    - run: cdk --version
    - run: npm i
    - run: cd iac; cdk deploy --require-approval=never
